theme: jekyll-theme-modernist
title: Carter Askelson's Data Analysis Porfolio	title: Carter Askelson's Data Analysis Porfolio
description: Thank you taking the time to check out some of the Projects that I've been working on.  	description: Thank you taking the time to check out some of the Projects that I've been working on.                                       Let me know if you have any questions!
Let me know if you have any questions!	
