theme: jekyll-theme-modernist
title: Welcome to Carter-Askelson's Homepage!
description: Thank you taking the time to check out some of the projjects that I've been working on.  Let me know if you have any questions!
